### ISSUE TITLE
[Feat] Spring Security, JWT 설정

### ISSUE THREAD

**Issue by ChooSeoyeon** [Beach-Combine/Backend#1]
## 📌  Description
- Spring Security, JWT 설정

## 📝  To-do
- [x] Spring Security 설정
- [x] CORS 설정
- [x] 사용자 엔티티, 컨트롤러, 서비스, 리포지토리 계층 생성
- [x] error enum 객체 활용
