### ISSUE TITLE
[Feat] 튜토리얼 기능 구현

### ISSUE THREAD

**Issue by ChooSeoyeon** [Beach-Combine/Backend#107]
## 📌  Description
- 사용자는 회원가입 후 사이트 최초 접속 시 튜토리얼이 뜬다.
- 최초 접속 이후엔 튜토리얼이 뜨지 않는다. 
## 📝  To-do
- [x] 튜토리얼 완료 여부 필드 추가. default는 false
- [x] 튜토리얼 완료 API 구현. 튜토리얼 종료하면서 해당 API 호출 시, 완료했단 정보를 DB에 저장
- [x] 로그인 시에, 튜토리얼 완료 여부를 알려주게 로그인 API response 수정

**Comment by ChooSeoyeon** [comment]
`alter table member add column tutorial_completed boolean default 0;`
