### ISSUE TITLE
[Feat] 이미지 업로드 구현

### ISSUE THREAD

**Issue by ChooSeoyeon** [Beach-Combine/Backend#23]
## 📌  Description
- 사용자가 업로드한 이미지는 Google Cloud Storage에 저장된다.

## 📝  To-do
- [x] Google Cloud Storage 설정 적용
- [x] 회원 정보 수정 API에 이미지 업로드 적용
- [x] 회원 정보 조회 API에 이미지 처리 적용
