### ISSUE TITLE
[Feat] 공공데이터포털 쓰레기통 정보 가져오기

### ISSUE THREAD

**Issue by pingowl** [Beach-Combine/Backend#32]
## 📌  Description
- 사용자가 청소 기록에 이용하는 쓰레기통 정보 중 일부는 공공데이터포털 데이터에서 가져온다.

## 📝  To-do
- [x] 데이터 API 적용
- [x] env.properties 에 serviceKey 저장
- [x] JSON 파싱
- [x] 구글 Geocoding API 추가 (반환된 한국어 주소 -> 좌표값 변환)
