### ISSUE TITLE
[Feat] 해변 근처 인증하기

### ISSUE THREAD

**Issue by pingowl** [Beach-Combine/Backend#51]
## 📌  Description
- 사용자는 청소할 해변 선택 후 현재위치가 해변근처에 포함되는지 인증받아야 한다.
## 📝  To-do
- [x] 해변 위치정보 DB에 저장
- [x] 해변 인정 범위 DB에 저장
- [x] 해변 근처 인증 API 구현
