### ISSUE TITLE
[Feat] 쓰레기통 인증하기 API

### ISSUE THREAD

**Issue by pingowl** [Beach-Combine/Backend#63]
## 📌  Description
- 관리자는 사용자가 신고한 쓰레기통을 인증할 수 있다.
## 📝  To-do
- [x] 쓰레기통 인증하기 구현
- [x]  역 지오코딩 API 사용
- [x]  인증 후 쓰레기통 상세주소 필드 저장
