### ISSUE TITLE
[Feat] 잔여 포인트 조회, 카드 목록 조회 API

### ISSUE THREAD

**Issue by ChooSeoyeon** [Beach-Combine/Backend#68]
## 📌  Description
- 사용자는 마이페이지에서 잔여 포인트를 조회할 수 있다.
- 사용자는 마이페이지에서 구매 가능한 카드 목록을 조회할 수 있다.
## 📝  To-do
- [x] Giftcard, Purchase, Store 엔티티 추가
- [x] 잔여 포인트 조회 API 구현
- [x]  카드 목록 조회 API 구현
- [x] 카드 더미 데이터 넣기
