### ISSUE TITLE
[Feat] 카드 구매 기능

### ISSUE THREAD

**Issue by ChooSeoyeon** [Beach-Combine/Backend#70]
## 📌  Description
- 사용자는 카드를 구매하고, 구매한 목록을 확인할 수 있다.

## 📝  To-do
- [x] 카드 구매하기  API 구현
- [x] 카드 구매 목록 조회 API 구현
- [x] 랭킹 테스트 위해 사용자 더미데이터 넣기
