### ISSUE TITLE
[Chore] 배지 이미지 대신 해변 아이디 반환

### ISSUE THREAD

**Issue by ChooSeoyeon** [Beach-Combine/Backend#91]
## 📌  Description
- 배지 이미지 대신 해변 아이디를 반환하고, 프론트에서 해변 아이디를 보고 해당 해변의 배지 이미지를 띄운다.
- 배지를 서버에서 저장한 이미지로 보내주는 방법도 있지만, 로딩 이슈와 배지가 수정될 일이 적다는 이유로 프론트에서 이미지를 띄어주기로 결정했다.
## 📝  To-do
- [x] 마이페이지 - (지도) 청소한 해변 마커 조회 :  배지 이미지 반환 -> 해변 id 반환으로 수정
- [x] 마이페이지 - 전체 청소 기록 목록 조회
- [x] 홈 - 리워드 조회 :  삭제

**Comment by ChooSeoyeon** [comment]
홈 -> 삭제
히스토리 -> 보민님 작업물에 들어 있음
마이페이지 -> 이미 보내고 있음
